.phony: run clean build

export

build:
	cd /usr/src/myapp/$(TARGET_DIRECTORY); make --makefile=Makefile.docker

run:
	cd /usr/src/myapp/$(TARGET_DIRECTORY); make --makefile=Makefile.docker run 

clean:
	cd /usr/src/myapp/$(TARGET_DIRECTORY); make --makefile=Makefile.docker clean
	
