
MODULE_NAME			= test_native
SERIAL_PORT 		= /dev/tty.usbmodem143201
PLATFORM			= native
#/dev/ttyACM0
#/dev/tty.usbmodem146201
#COM4
CONSOLE_BAUDRATE	= 115200

export 
include $(R2D2_ROOT_DIR)/modules/Makefile.module
