
MODULE_NAME			= test_native
SERIAL_PORT 		= /dev/tty.usbmodem143201 	#/dev/ttyACM0
												#/dev/tty.usbmodem146201
												#COM4
PLATFORM			= native

CONSOLE_BAUDRATE	= 115200

export 
include $(R2D2_ROOT_DRIVE)$(R2D2_ROOT_DIR)/modules/Makefile.module
